name: Deploy Angular app (OIDC)

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # 🔑 required for OIDC
      contents: read       # checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Clean and build Angular
        run: |
          rm -rf dist
          npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::544893999043:role/GitHub-Action-Role
          aws-region: ap-south-1

      - name: Upload to S3
        run: aws s3 cp dist/stradux/ s3://cross-border-platform/ --recursive

      # - name: Invalidate CloudFront cache
      #   run: |
      #     aws cloudfront create-invalidation \
      #       --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
      #       --paths "/*"
